spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    timeout: 3000
    #    sentinel: #哨兵模式
    #      master: mymaster #主服务器所在集群名称
    #      nodes: 192.168.218.133:26379,192.168.218.133:26380,192.168.218.133:26381
    cluster: #集群模式
      nodes: 192.168.218.131:8001,192.168.218.131:8004,192.168.218.132:8002,192.168.218.132:8007,192.168.218.133:8003,192.168.218.133:8006
    #    host: 192.168.218.132单机默认
    #    port: 8008
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000


server:
  port: 8080

rocketmq:
  name-server: 192.168.218.131:9876;192.168.218.132:9876;192.168.218.133:9876
  producer:
    group: springBootGroup

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.example.action.entity

logging:
  level:
    com: DEBUG
